#ifndef ESP_WIFI_TYPES_H__
#define ESP_WIFI_TYPES_H__

#define ESP_WIFI_AP_SSID "ESP_NOTIFICATION"
#define ESP_WIFI_AP_PASSD "PasswordEsp32."
#define ESP_WIFI_AP_MAX_STA 2
#define ESP_WIFI_AP_CHANNEL 0
#define ESP_WIFI_AP_AUTH_MODE WIFI_AUTH_WPA2_PSK

#define ESP_WIFI_STA_RETRYS 3
#define WIFI_CONNECTED_BIT BIT0
#define WIFI_FAIL_BIT BIT1
#define WIFI_AP_START BIT2

#endif